### ISSUE TITLE
unable to install linux-system-roles.storage role because of `can only concatenate list (not "dict") to list`

### ISSUE THREAD

**Issue by jhutar** [linux-system-roles/storage#258]
I'm unable to install/update the role because of this ansible-galaxy error:

```
sh-5.0$ ansible-galaxy role install -r requirements.yml --force -vvv
[DEPRECATION WARNING]: Ansible will require Python 3.8 or newer on the controller starting with Ansible 2.12. Current version: 3.7.9 (default, Aug 19 2020, 17:05:11) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]. This feature will be removed from ansible-core in version 2.12. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ansible-galaxy [core 2.11.7] 
  config file = /home/jenkins/workspace/ContPerf70/ansible.cfg
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  ansible collection location = /home/jenkins/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-galaxy
  python version = 3.7.9 (default, Aug 19 2020, 17:05:11) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.0.3
  libyaml = True
Using /home/jenkins/workspace/ContPerf70/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]callback_whitelist option, normalizing names to new standard, use callbacks_enabled instead. This feature will be removed from ansible-
core in version 2.15. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Reading requirement file at '/home/jenkins/workspace/ContPerf70/requirements.yml'
found role {'name': 'linux-system-roles.storage', 'src': 'https://github.com/jhutar/storage.git', 'version': 'origin/master', 'scm': 'git'} in yaml file
Opened /home/jenkins/.ansible/galaxy_token
Starting galaxy role install process
Processing role linux-system-roles.storage 
- changing role linux-system-roles.storage from origin/master to origin/master
archiving ['/usr/bin/git', 'archive', '--prefix=linux-system-roles.storage/', '--output=/home/jenkins/.ansible/tmp/ansible-local-485220prt3mnh/tmpmr69zjuf.tar', 'origin/master']
- extracting linux-system-roles.storage to /home/jenkins/.ansible/roles/linux-system-roles.storage
- linux-system-roles.storage (origin/master) was installed successfully
ERROR! Unexpected Exception, this is probably a bug: can only concatenate list (not "dict") to list
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 135, in <module>
    exit_code = cli.run()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 552, in run
    return context.CLIARGS['func']()
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 75, in method_wrapper
    return wrapped_method(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1180, in execute_install
    self._execute_install_role(role_requirements)
  File "/usr/local/lib/python3.7/site-packages/ansible/cli/galaxy.py", line 1265, in _execute_install_role
    role_dependencies = (role.metadata.get('dependencies') or []) + role.requirements
TypeError: can only concatenate list (not "dict") to list
```

This is mine requirements.yml file:

```
---
roles:
  - name: linux-system-roles.storage
collections: []
...
```

I think it is caused by `meta/requirements.yml` file. When I forked and removed the file, it works fine (I have `ansible.posix` installed).

I think this is hitting this Ansible issue from which I concluded that there is no "official" way how role could depend on collection: https://github.com/ansible/ansible/issues/62847 also https://github.com/ansible/ansible/issues/76030

**Comment by richm** [comment]
> I think this is hitting this Ansible issue from which I concluded that there is no "official" way how role could depend on collection: https://github.com/ansible/ansible/issues/62847 also https://github.com/ansible/ansible/issues/76030

Correct.  I'm not sure how to handle this - there are a few system roles that have dependencies on collections.  I was thinking about perhaps using a file `meta/collection-requirements.yml` - non-standard, but at least users would be able to install the role, then look for and run `ansible-galaxy collection install -r /path/to/roles/ROLENAME/meta/collection-requirements.yml`

Any ideas?

**Comment by tyll** [comment]
@jhutar you can also install the role via the fedora.linux_system_roles collection.

**Comment by jhutar** [comment]
Thank you @tyll . Did not knew that!
